export const VEHICLES_DATA = [
  {
    id: '1',
    name: 'Avatr 12',
    brand: 'Avatr',
    price: 45000,
    image: 'https://via.placeholder.com/400x300?text=Avatr+12',
    rating: 4.8,
    reviews: 45,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    year: 2024,
    color: 'Pearl White',
  },
  {
    id: '2',
    name: 'BYD Song',
    brand: 'BYD',
    price: 35000,
    image: 'https://via.placeholder.com/400x300?text=BYD+Song',
    rating: 4.7,
    reviews: 38,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    year: 2024,
    color: 'Midnight Black',
  },
  {
    id: '3',
    name: 'XPeng G9',
    brand: 'XPeng',
    price: 52000,
    image: 'https://via.placeholder.com/400x300?text=XPeng+G9',
    rating: 4.9,
    reviews: 52,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    year: 2024,
    color: 'Deep Gray',
  },
  {
    id: '4',
    name: 'Geely Geometry',
    brand: 'Geely',
    price: 38000,
    image: 'https://via.placeholder.com/400x300?text=Geely+Geometry',
    rating: 4.6,
    reviews: 32,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    year: 2024,
    color: 'Cosmic Blue',
  },
  {
    id: '5',
    name: 'NIO ET5',
    brand: 'NIO',
    price: 55000,
    image: 'https://via.placeholder.com/400x300?text=NIO+ET5',
    rating: 4.9,
    reviews: 48,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    year: 2024,
    color: 'Pearl White',
  },
  {
    id: '6',
    name: 'Xiaomi SU7',
    brand: 'Xiaomi',
    price: 48000,
    image: 'https://via.placeholder.com/400x300?text=Xiaomi+SU7',
    rating: 4.8,
    reviews: 41,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    year: 2024,
    color: 'Titanium Gray',
  },
  {
    id: '7',
    name: 'Changan UNI-V',
    brand: 'Changan',
    price: 32000,
    image: 'https://via.placeholder.com/400x300?text=Changan+UNI-V',
    rating: 4.5,
    reviews: 28,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    year: 2024,
    color: 'Sunset Orange',
  },
  {
    id: '8',
    name: 'Jetour Dashing',
    brand: 'Jetour',
    price: 36000,
    image: 'https://via.placeholder.com/400x300?text=Jetour+Dashing',
    rating: 4.6,
    reviews: 35,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    year: 2024,
    color: 'Red Metallic',
  },
  {
    id: '9',
    name: 'Chery Tiggo 8',
    brand: 'Chery',
    price: 34000,
    image: 'https://via.placeholder.com/400x300?text=Chery+Tiggo+8',
    rating: 4.7,
    reviews: 39,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    year: 2024,
    color: 'Silver',
  },
  {
    id: '10',
    name: 'MG HS Plus',
    brand: 'MG',
    price: 37000,
    image: 'https://via.placeholder.com/400x300?text=MG+HS+Plus',
    rating: 4.6,
    reviews: 36,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    year: 2024,
    color: 'Pearl Black',
  },
  {
    id: '11',
    name: 'Avatr 11',
    brand: 'Avatr',
    price: 42000,
    image: 'https://via.placeholder.com/400x300?text=Avatr+11',
    rating: 4.8,
    reviews: 44,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    year: 2024,
    color: 'Glacier White',
  },
  {
    id: '12',
    name: 'BYD Qin',
    brand: 'BYD',
    price: 33000,
    image: 'https://via.placeholder.com/400x300?text=BYD+Qin',
    rating: 4.7,
    reviews: 37,
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    year: 2024,
    color: 'Obsidian Black',
  },
];
