export const VEHICLE_DETAILS = {
  '1': {
    id: '1',
    name: 'Avatr 12',
    brand: 'Avatr',
    price: 45000,
    year: 2024,
    color: 'Pearl White',
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    gallery: [
      'https://via.placeholder.com/800x600?text=Avatr+12+Front',
      'https://via.placeholder.com/800x600?text=Avatr+12+Side',
      'https://via.placeholder.com/800x600?text=Avatr+12+Interior',
      'https://via.placeholder.com/800x600?text=Avatr+12+Rear',
      'https://via.placeholder.com/800x600?text=Avatr+12+Engine',
    ],
    rating: 4.8,
    reviews: 45,
    description:
      'Experience the future with the Avatr 12, a revolutionary electric vehicle combining cutting-edge technology with luxurious comfort. Perfect for discerning drivers seeking premium performance and innovation.',
    specifications: {
      engine: {
        type: 'Electric Motor',
        power: '250 kW',
        torque: '540 N⋅m',
        acceleration: '0-100 km/h in 5.2 seconds',
        topSpeed: '230 km/h',
        battery: '116.8 kWh',
      },
      performance: {
        range: '600 km',
        fuelConsumption: 'Electric',
        emissions: '0 g/km CO₂',
        driveType: 'Dual Motor AWD',
      },
      dimensions: {
        length: '4,755 mm',
        width: '1,935 mm',
        height: '1,615 mm',
        wheelbase: '2,975 mm',
        groundClearance: '220 mm',
        fuelTankCapacity: 'N/A',
      },
      interior: {
        seatingCapacity: '5',
        material: 'Premium Leather',
        features: [
          'Panoramic Glass Roof',
          '15.6" Digital Dashboard',
          'AI Voice Control',
          'Wireless Charging',
          'Ambient Lighting',
          'Power Seats with Memory',
        ],
      },
      safety: [
        'Advanced Collision Avoidance',
        'Automatic Emergency Braking',
        '360° Surround View Camera',
        'Blind Spot Monitoring',
        'Lane Keep Assist',
        '9 Airbags',
        'Traction Control',
      ],
    },
    features: [
      'Smart Key Entry',
      'Panoramic Sunroof',
      'Heated Leather Seats',
      'Premium Sound System',
      'Wireless Phone Charging',
      'Adaptive Suspension',
      'LED Headlights',
      'Climate Control',
    ],
  },
  '2': {
    id: '2',
    name: 'BYD Song',
    brand: 'BYD',
    price: 35000,
    year: 2024,
    color: 'Midnight Black',
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    gallery: [
      'https://via.placeholder.com/800x600?text=BYD+Song+Front',
      'https://via.placeholder.com/800x600?text=BYD+Song+Side',
      'https://via.placeholder.com/800x600?text=BYD+Song+Interior',
      'https://via.placeholder.com/800x600?text=BYD+Song+Rear',
    ],
    rating: 4.7,
    reviews: 38,
    description:
      'The BYD Song combines hybrid efficiency with premium comfort. Advanced technology and elegant design make it the ideal choice for eco-conscious luxury seekers.',
    specifications: {
      engine: {
        type: 'Hybrid (1.5L Turbocharged + Electric)',
        power: '380 kW Combined',
        torque: '600 N⋅m',
        acceleration: '0-100 km/h in 6.1 seconds',
        topSpeed: '210 km/h',
        battery: '50 kWh',
      },
      performance: {
        range: '1000 km (Combined)',
        fuelConsumption: '5.2 L/100km',
        emissions: '120 g/km CO₂',
        driveType: 'Front Wheel Drive',
      },
      dimensions: {
        length: '4,650 mm',
        width: '1,860 mm',
        height: '1,590 mm',
        wheelbase: '2,850 mm',
        groundClearance: '210 mm',
        fuelTankCapacity: '50 L',
      },
      interior: {
        seatingCapacity: '5',
        material: 'Premium Fabric & Leather',
        features: [
          'Smart Climate Control',
          '12.8" Touchscreen',
          'Voice Commands',
          'Rearview Camera',
          'Power Windows',
          'Cruise Control',
        ],
      },
      safety: [
        'ABS with EBD',
        'Multiple Airbags',
        'Electronic Stability Control',
        'Hill Start Assist',
        'Parking Sensors',
        'Reverse Camera',
      ],
    },
    features: [
      'Panoramic Sunroof',
      'Smart Key',
      'Rear Climate Control',
      'Touchscreen Infotainment',
      'Backup Camera',
      'Cruise Control',
      'LED Lights',
      'All-Wheel Drive',
    ],
  },
  '3': {
    id: '3',
    name: 'XPeng G9',
    brand: 'XPeng',
    price: 52000,
    year: 2024,
    color: 'Deep Gray',
    mileage: 0,
    transmission: 'Automatic',
    fuelType: 'Electric',
    gallery: [
      'https://via.placeholder.com/800x600?text=XPeng+G9+Front',
      'https://via.placeholder.com/800x600?text=XPeng+G9+Side',
      'https://via.placeholder.com/800x600?text=XPeng+G9+Interior',
      'https://via.placeholder.com/800x600?text=XPeng+G9+Rear',
      'https://via.placeholder.com/800x600?text=XPeng+G9+Engine',
    ],
    rating: 4.9,
    reviews: 52,
    description:
      'The XPeng G9 is the pinnacle of electric luxury. With advanced autonomous driving, 5-minute fast charging, and intelligent design, it redefines premium mobility.',
    specifications: {
      engine: {
        type: 'Dual Electric Motors',
        power: '350 kW',
        torque: '660 N⋅m',
        acceleration: '0-100 km/h in 4.3 seconds',
        topSpeed: '250 km/h',
        battery: '118 kWh',
      },
      performance: {
        range: '650 km',
        fuelConsumption: 'Electric',
        emissions: '0 g/km CO₂',
        driveType: 'All-Wheel Drive',
      },
      dimensions: {
        length: '4,891 mm',
        width: '1,981 mm',
        height: '1,680 mm',
        wheelbase: '3,005 mm',
        groundClearance: '230 mm',
        fuelTankCapacity: 'N/A',
      },
      interior: {
        seatingCapacity: '5',
        material: 'Premium Leather',
        features: [
          'Panoramic Glass Roof',
          '15.6" AMOLED Display',
          'AI Assistant',
          'Wireless Charging Pad',
          'Scene Lighting System',
          'Reclining Rear Seats',
        ],
      },
      safety: [
        'Autonomous Driving Level 3',
        'LiDAR + Camera System',
        'Automatic Emergency Braking',
        '360° Monitoring System',
        'Adaptive Cruise Control',
        '10 Airbags',
        'All-Round Protection',
      ],
    },
    features: [
      'Autonomous Driving Ready',
      'Ultra-Fast Charging (5 min)',
      'Heated/Cooled Seats',
      'Premium Audio System',
      'Smart Glass Roof',
      'Over-the-Air Updates',
      'Energy Recovery Braking',
      'Adaptive Suspension',
    ],
  },
};

export const FINANCE_OPTIONS = [
  { months: 12, rate: 8.5 },
  { months: 24, rate: 8.5 },
  { months: 36, rate: 8.5 },
  { months: 48, rate: 9.0 },
  { months: 60, rate: 9.0 },
];
